#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

mkdir -p _input
cd _input

FILES=(
  "_assets/api.js"
  "_assets/common.js"
  "_assets/api.css"
  "_assets/common.css"
  "_assets/styles.css"
)

for f in ${FILES[@]}
do
  dir=`dirname $f`
  mkdir -p $dir
  wget -O $f http://kotlinlang.org/$f
done

set +e
wget --mirror -k -nH https://kotlinlang.org/api/latest/jvm/stdlib/
wget_status=$?
set -e

if [ $wget_status -eq 8 ]; then
  # https://www.gnu.org/software/wget/manual/html_node/Exit-Status.html
  echo "wget partially failed (exit status $wget_status)... continuing."
elif [ $wget_status -ne 0 ]; then
  echo "wget failed (exit status $wget_status)"
  exit 1
fi

if [ ! -d _javadoc ]; then
  wget -O - https://github.com/JetBrains/kotlin/archive/gh-pages.zip | bsdtar -xvf-
  mv kotlin-gh-pages _javadoc
fi

# Remove non-API pages
rm -rf ./community
rm -rf ./eap
rm -rf ./education
rm -rf ./foundation
rm -rf ./lp
rm ./security.html
rm ./robots.txt

